# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
   name: default
   demands:
    - agent.name -equals LAPTOP-5LDNLO73

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-FreeTier-Jcontti'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account list -o table'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: false

- task: CmdLine@2
  inputs:
    script: |
      dir
      cd scripts
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    commandOptions: '-var serviceprinciple_id=$SERVICE_PRINCIPAL \     -var serviceprinciple_key="$SERVICE_PRINCIPAL_SECRET" \     -var tenant_id=$TENTANT_ID \     -var subscription_id=$SUBSCRIPTION \     -var ssh_key="$SSH_KEY"'
    allowTelemetryCollection: false