# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
   name: default
   demands:
    - agent.name -equals LAPTOP-5LDNLO73

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-FreeTier-Jcontti'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account list -o table'
  displayName: 'Azure Subscription list'


- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: false
  displayName: 'Terraform INIT'

- task: CmdLine@2
  inputs:
    script: 'echo $free-subscription-kv) > secret.txt'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-FreeTier-Jcontti'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
            $SERVICE_PRINCIPAL=$(az keyvault secret show --name service-principal-kv --vault-name terraform-aks-kv --query value -o tsv)
            
            $SERVICE_PRINCIPAL_SECRET=$(az keyvault secret show --name service-principal-secret-kv --vault-name terraform-aks-kv --query value -o tsv)
            
            $SUBSCRIPTION=$(az keyvault secret show --name free-subscription-kv --vault-name terraform-aks-kv --query value -o tsv)
            
            $TENTANT_ID=$(az keyvault secret show --name free-tentant-kv --vault-name terraform-aks-kv --query value -o tsv)
            
            $SSH_KEY=$(az keyvault secret show --name ssh-key-kv --vault-name terraform-aks-kv --query value -o tsv)
        
            echo $SUBSCRIPTION
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    commandOptions: '-var serviceprinciple_id=$SERVICE_PRINCIPAL \     -var serviceprinciple_key="$SERVICE_PRINCIPAL_SECRET" \     -var tenant_id=$TENTANT_ID \     -var subscription_id=$SUBSCRIPTION \     -var ssh_key="$SSH_KEY"'
    allowTelemetryCollection: false