# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
   name: default
   demands:
    - agent.name -equals LAPTOP-5LDNLO73

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-FreeTier-Jcontti'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account list -o table'
  displayName: 'Azure Subscription list'


- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: false
  displayName: 'Terraform INIT'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure-FreeTier-Jcontti'
    KeyVaultName: 'terraform-aks-kv'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  inputs:
    script: |
      echo $(service-principal-secret-kv) > sp-secret.txt
      echo $(service-principal-kv) > sp.txt
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    commandOptions: '-var serviceprinciple_id=$(service-principal-kv) -var serviceprinciple_key="$(service-principal-secret-kv)" -var tenant_id=$(free-tentant-kv) -var subscription_id=$(free-subscription-kv) -var ssh_key="$(ssh-key-kv)"'
    allowTelemetryCollection: false