# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
   name: default
   demands:
    - agent.name -equals LAPTOP-5LDNLO73

steps:

- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: false
  displayName: 'Terraform INIT'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure-FreeTier-Jcontti'
    KeyVaultName: 'terraform-aks-kv'
    SecretsFilter: '*'
    RunAsPreJob: false
  displayName: 'Retrieve secretS from Key Vault'

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    commandOptions: '-var serviceprinciple_id=$(service-principal-kv) -var serviceprinciple_key="$(service-principal-secret-kv)" -var tenant_id=$(free-tentant-kv) -var subscription_id=$(free-subscription-kv) -var ssh_key="$(ssh-key-kv)"'
    allowTelemetryCollection: false
  displayName: 'Terraform PLAN'

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    commandOptions: '-var serviceprinciple_id=$(service-principal-kv) -var serviceprinciple_key="$(service-principal-secret-kv)" -var tenant_id=$(free-tentant-kv) -var subscription_id=$(free-subscription-kv) -var ssh_key="$(ssh-key-kv)"'
    allowTelemetryCollection: true
  displayName: 'Terraform APPLY'